# https://pnpm.io/settings

shellEmulator: true
dedupePeers: true
trustPolicy: no-downgrade
ignoreWorkspaceRootCheck: true

packages:
  - examples/**
  - playground
  - test/fixture
  - test/minimal

allowBuilds: {}

peerDependencyRules:
  allowedVersions:
    vite: "8"
    typescript: "6"

trustPolicyExclude:
  - "semver@6.3.1"
