# https://pnpm.io/settings

ignoreWorkspaceRootCheck: true
shellEmulator: true
dedupePeers: true

packages:
  - examples/**
  - playground
  - test/fixture
  - test/minimal

allowBuilds: {}

peerDependencyRules:
  allowedVersions:
    vite: "8"
    typescript: "6"
