// Auto generated using gen-node-compat.ts on 2025-10-05
// Source: https://platform-node-compat.pi0.workers.dev/
// Do not edit this file manually

// prettier-ignore
export const builtnNodeModules = [
  "_http_agent",
  "_http_client",
  "_http_common", // Missing exports: CRLF, HTTPParser, freeParser, isLenient, parsers, prepareError
  "_http_incoming", // Missing exports: readStart, readStop
  "_http_outgoing",
  "_http_server",
  "_stream_duplex",
  "_stream_passthrough",
  "_stream_readable",
  "_stream_transform",
  "_stream_writable",
  "_tls_common",
  "_tls_wrap", // Missing exports: Server, createServer
  "assert", // Missing exports: Assert, CallTracker
  "assert/strict", // Missing exports: Assert, CallTracker
  "async_hooks",
  "buffer",
  "constants", // Missing exports: O_DIRECT, O_NOATIME, RTLD_DEEPBIND, SIGPOLL, SIGPWR, SIGSTKFLT, defaultCipherList
  "crypto",
  "diagnostics_channel",
  "dns", // Missing exports: resolveTlsa
  "dns/promises", // Missing exports: resolveTlsa
  "events", // Missing exports: captureRejections, init
  "fs",
  "fs/promises",
  "http",
  "http2",
  "https",
  "module",
  "net",
  "os",
  "path",
  "path/posix",
  "path/win32",
  "process",
  "querystring",
  "stream",
  "stream/consumers",
  "stream/promises",
  "stream/web",
  "string_decoder",
  "timers",
  "timers/promises",
  "tls", // Missing exports: getCACertificates, setDefaultCACertificates
  "url", // Missing exports: fileURLToPathBuffer
  "util", // Missing exports: diff, setTraceSigInt
  "util/types",
  "zlib", // Missing exports: ZstdCompress, ZstdDecompress, createZstdCompress, createZstdDecompress, zstdCompress, zstdCompressSync, zstdDecompress, zstdDecompressSync
];

// prettier-ignore
export const unsupportedNodeModules = [
  "_stream_wrap",
  "child_process",
  "cluster",
  "console",
  "dgram",
  "domain",
  "inspector",
  "inspector/promises",
  "perf_hooks",
  "punycode",
  "readline",
  "readline/promises",
  "repl",
  "sys",
  "trace_events",
  "tty",
  "v8",
  "vm",
  "wasi",
  "worker_threads",
  "sqlite",
];
