// Auto generated using gen-node-compat.ts on 2025-10-05
// Source: https://platform-node-compat.deno.dev/
// Do not edit this file manually

// prettier-ignore
export const builtnNodeModules = [
  "_http_agent",
  "_http_common", // Missing exports: freeParser, isLenient, parsers, prepareError
  "_http_outgoing",
  "_http_server", // Missing exports: Server, ServerResponse, httpServerPreClose, kConnectionsCheckingInterval, kServerResponse, setupConnectionsTracking, storeHTTPOptions
  "_stream_duplex", // Missing exports: from, fromWeb, toWeb
  "_stream_passthrough",
  "_stream_readable", // Missing exports: ReadableState, from, fromWeb, toWeb, wrap
  "_stream_transform",
  "_stream_writable", // Missing exports: WritableState, fromWeb, toWeb
  "_tls_common", // Missing exports: SecureContext, translatePeerCertificate
  "_tls_wrap",
  "assert", // Missing exports: Assert, CallTracker, partialDeepStrictEqual
  "assert/strict", // Missing exports: Assert, CallTracker, partialDeepStrictEqual
  "async_hooks",
  "buffer", // Missing exports: File, resolveObjectURL
  "child_process",
  "cluster",
  "console", // Missing exports: context, createTask
  "constants", // Missing exports: O_DIRECT, O_NOATIME, defaultCipherList
  "crypto", // Missing exports: Cipher, Decipher
  "dgram",
  "diagnostics_channel", // Missing exports: Channel
  "dns", // Missing exports: getDefaultResultOrder, lookupService, resolveTlsa
  "dns/promises", // Missing exports: getDefaultResultOrder, lookupService, resolveTlsa
  "domain",
  "events", // Missing exports: captureRejections, getMaxListeners, init, usingDomains
  "fs", // Missing exports: FileReadStream, FileWriteStream, fchmod, fchmodSync, fchown, fchownSync, glob, globSync, lchmod, lchmodSync, lchown, lchownSync, openAsBlob
  "fs/promises", // Missing exports: glob, lchmod, lchown, lutimes, statfs
  "http", // Missing exports: CloseEvent, MessageEvent, WebSocket, setMaxIdleHTTPParsers
  "http2", // Missing exports: performServerHandshake
  "https",
  "inspector", // Missing exports: NetworkResources
  "inspector/promises", // Missing exports: NetworkResources
  "module", // Missing exports: SourceMap, constants, enableCompileCache, findPackageJSON, flushCompileCache, getCompileCacheDir, getSourceMapsSupport, registerHooks, runMain, setSourceMapsSupport, stripTypeScriptTypes, syncBuiltinESMExports
  "net",
  "os",
  "path", // Missing exports: matchesGlob
  "path/posix", // Missing exports: matchesGlob
  "path/win32", // Missing exports: matchesGlob
  "perf_hooks", // Missing exports: Performance, PerformanceMark, PerformanceMeasure, PerformanceObserverEntryList, PerformanceResourceTiming, createHistogram
  "process", // Missing exports: assert, availableMemory, binding, config, constrainedMemory, debugPort, domain, execve, exitCode, features, finalization, getActiveResourcesInfo, getgroups, hasUncaughtExceptionCaptureCallback, initgroups, loadEnvFile, moduleLoadList, openStdin, ppid, reallyExit, ref, release, report, resourceUsage, setSourceMapsEnabled, setUncaughtExceptionCaptureCallback, setegid, seteuid, setgid, setgroups, setuid, sourceMapsEnabled, threadCpuUsage, title, unref, uptime
  "punycode",
  "querystring",
  "readline",
  "readline/promises",
  "repl", // Missing exports: Recoverable, writer
  "sqlite", // Missing exports: StatementSync, backup
  "stream", // Missing exports: destroy, promises
  "stream/consumers",
  "stream/promises",
  "stream/web",
  "string_decoder",
  "sys", // Missing exports: MIMEParams, MIMEType, diff, getCallSite, getSystemErrorMap, getSystemErrorMessage, parseEnv, setTraceSigInt, transferableAbortController, transferableAbortSignal
  "timers", // Missing exports: active, enroll, unenroll
  "timers/promises",
  "tls", // Missing exports: SecureContext, convertALPNProtocols, getCACertificates, setDefaultCACertificates
  "trace_events",
  "tty",
  "url", // Missing exports: fileURLToPathBuffer
  "util", // Missing exports: MIMEParams, MIMEType, diff, getCallSite, getSystemErrorMap, getSystemErrorMessage, parseEnv, setTraceSigInt, transferableAbortController, transferableAbortSignal
  "util/types", // Missing exports: isExternal
  "v8", // Missing exports: GCProfiler, getCppHeapStatistics, isStringOneByteRepresentation, promiseHooks, queryObjects, setHeapSnapshotNearHeapLimit, startupSnapshot
  "vm",
  "wasi",
  "worker_threads", // Missing exports: isInternalThread, isMarkedAsUntransferable, markAsUncloneable, postMessageToThread, threadName
  "zlib", // Missing exports: ZstdCompress, ZstdDecompress, createZstdCompress, createZstdDecompress, zstdCompress, zstdCompressSync, zstdDecompress, zstdDecompressSync
];

// prettier-ignore
export const unsupportedNodeModules = [
  "_http_client",
  "_http_incoming",
  "_stream_wrap",
];
