contact_links:
  - name: 💬 Discussions
    url: https://github.com/unjs/nitropack/discussions
    about: Use discussions if you have an idea for improvement and asking questions
  - name: 🔗 Nuxt related Issues
    url: https://github.com/nuxt/nuxt/issues/new/choose
    about: Please open an issue in nuxt/nuxt to discuss
