name = "nitro-test"

compatibility_date = "2024-09-19"

# [[durable_objects.bindings]]
# name = "$DurableObject"
# class_name = "$DurableObject"

# [[migrations]]
# tag = "v1"
# new_sqlite_classes = ["$DurableObject"]
