name: ci

on:
  push: { branches: [v2] }
  pull_request: { branches: [v2] }

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - run: npm i -g --force corepack && corepack enable
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with: { node-version: lts/*, cache: pnpm }
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
        if: ${{ matrix.os != 'windows-latest' }}
        with: { bun-version: latest }
      - uses: denoland/setup-deno@11b63cf76cfcafb4e43f97b6cad24d8e8438f62d # v1
        if: ${{ matrix.os != 'windows-latest' }}
        with: { deno-version: v2.x }
      - run: pnpm install
      - run: pnpm stub && pnpm lint
        if: ${{ matrix.os != 'windows-latest' }}
      - run: pnpm test:types
        if: ${{ matrix.os != 'windows-latest' }}
      - run: pnpm build
      - run: pnpm vitest --coverage
      # - uses: codecov/codecov-action@v3

  publish-pkg-pr-new:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with: { fetch-depth: 0 }
      - run: npm i -fg corepack && corepack enable
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with: { node-version: lts/*, cache: "pnpm" }
      - run: pnpm install
      - run: pnpm build
      - run: pnpm dlx pkg-pr-new publish || true

  publish:
    runs-on: ubuntu-latest
    permissions: { id-token: write, contents: read }
    needs: tests
    if: github.ref == 'refs/heads/v2' && github.event_name == 'push' && github.repository == 'nitrojs/nitro'
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with: { fetch-depth: 0 }
      - run: npm i -fg corepack && corepack enable
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with: { node-version: lts/*, cache: "pnpm" }
      - run: pnpm install
      - run: pnpm changelogen --bump --canary nightly
      - run: npm i -g npm@latest && npm publish --provenance --access public --tag latest
