name: ci

on:
  push: { branches: [v2] }
  pull_request: { branches: [v2] }

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: npm i -g --force corepack && corepack enable
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with: { node-version: lts/*, cache: pnpm }
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        if: ${{ matrix.os != 'windows-latest' }}
        with: { bun-version: latest }
      - uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5
        if: ${{ matrix.os != 'windows-latest' }}
        with: { deno-version: v2.x }
      - run: pnpm install
      - run: pnpm stub && pnpm lint
        if: ${{ matrix.os != 'windows-latest' }}
      - run: pnpm test:types
        if: ${{ matrix.os != 'windows-latest' }}
      - run: pnpm build
      - run: pnpm vitest --coverage
      # - uses: codecov/codecov-action@v3

  publish-pkg-pr-new:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with: { fetch-depth: 0 }
      - run: npm i -fg corepack && corepack enable
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with: { node-version: lts/*, cache: "pnpm" }
      - run: pnpm install
      - run: pnpm build
      - run: pnpm dlx pkg-pr-new publish || true

  publish:
    runs-on: ubuntu-latest
    permissions: { id-token: write, contents: read }
    needs: tests
    if: github.ref == 'refs/heads/v2' && github.event_name == 'push' && github.repository == 'nitrojs/nitro'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with: { fetch-depth: 0 }
      - run: npm i -fg corepack && corepack enable
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with: { node-version: lts/*, cache: "pnpm" }
      - run: pnpm install
      - run: pnpm changelogen --bump --canary nightly
      - run: npm i -g npm@latest && npm publish --provenance --access public --tag latest
